export const Strings = {
  SIGNUP_SCREEN: 'Let’s get you in!',
  CONTINUE_WITH_GOOGLE: 'Continue with Google',
  CONTINUE_WITH_FACEBOOK: 'Continue with Facebook',
  CONTINUE_WITH_APPLE: 'Continue with Apple',
  OR: 'or',
  OR_LOGIN: 'or login with',
  SIGNIN_WITH_EMAIL: 'Sign in with my email',
  DO_NOT_HAVE_ACCOUNT: 'Don’t have an account?',
  DO_NOT_HAVE_EMAIL: 'Didn’t receive any email?',
  SIGNUP: 'Sign up',
  RESEND_LINK: 'Resend Link',
  LOGIN: 'Login',
  SEND_LINK: 'Send Link',
  CHECK_MAIL_BUTTON: 'Check Email',
  RESET_PATTON: 'Reset Password',
  SIGNIN: 'Sign in',
  SIGNUP_EMAIL_SCREEN: 'Sign up',
  ACCOUNT_INFO: 'Account  Info',
  Welcome_Back: 'Welcome back',
  Login_Account: 'Login to your account',
  CREATE_NEW_ACCOUNT: 'Create your new account',
  USER_NAME: 'Username',
  EMAIL_ID: 'Email',
  RESET_PASSWORD_TEXT: 'We have sent you a link to reset your\npassword.',
  FORGOT_PASS_TEXT:
    'Enter the email associated with your account\nwe will send you an email with a link to reset\nyour password.',
  RESET_PASS_TEXT:
    'Your new password must be different\nfrom previous used passwords.',
  PASSWORD: 'Password',
  NEW_PASSWORD: 'New password',
  CON_PASSWORD: 'Confirm password',
  CHECK_MAIL: 'Check your email',
  CONFIRM_PASSWORD: 'Confirm password',
  ENTER_USER_NAME: 'Enter a username',
  ENTER_USER_EMAIL: 'Enter your email',
  ENTER_USER_PASSWORD: 'Enter a password',
  ENTER_USER_CONFIRM_PASSWORD: 'Confirm password',
  CREATE_NEW_PASSWORD: 'Create new password',
  BY_SIGNUP: 'By signing up, you have agreed to',
  UPDATE: 'Update',
  ZING_ZANG: 'Zing Zang Terms of Use and Privacity',
  Forgot_password: 'Forgot your password?',
  ALREADY_SIGNUP: 'Already have an account?',
  FORGOT_PASSWORD_HEADER: 'Forgot password?',
  RESET_PASSWORD_HEADER: 'Reset password',
  PASS_RESET: 'Password reset',
  PASS_RESET_SUCCESS: 'Your password has been reset successfully',
  VALIDATE_USER_NAME: 'Please enter your user name',
  VALIDATE_EMAIL: 'Please enter valid email id',
  VALIDATE_PASSWORD: 'Please enter valid password',
  VALIDATE_CONFIRM_PASSWORD: 'Please enter valid confirm password',
  REXX_AI: 'REXX AI',
  Rexx_Title: 'What would you like to do as your first project?',
  Rexx_Subtitle: 'Select one of the following options',
  Search: 'Search',
  Remix: 'Select the song you would like to remix',
  CONTINUE: 'Continue',
  PartSongTitle: 'Select part of the song',
  PartSongSubTitle: 'Select one of the following part below to sing',
};
