import CREATE_NEW_PROJECT from './CREATE_NEW_PROJECT.svg';
import LOAD_PROJECT from './LOAD_PROJECT.svg';

import REMIX_SONG from './REMIX_SONG.svg';
import GENERATE_TRACK from './GENERATE_TRACK.svg';

export const IMAGES_SVG = {
  CREATE_NEW_PROJECT: CREATE_NEW_PROJECT,
  LOAD_PROJECT: LOAD_PROJECT,
  GENERATE_TRACK: GENERATE_TRACK,
  REMIX_SONG: REMIX_SONG,
};
